stages:
  - preparation
  - building
  - checking
  - testing

# This image was made for Laravel but works for Sylius as well
# https://github.com/edbizarro/gitlab-ci-pipeline-php
image: edbizarro/gitlab-ci-pipeline-php:7.4-alpine

variables:
  MYSQL_ROOT_PASSWORD: your-root-password
  MYSQL_USER: your-mysql-user
  DATABASE_URL: 'mysql://your-mysql-user:your-mysql-user-password@your-db-ip/sylius_%kernel.environment%'

  COMPOSER_MEMORY_LIMIT: -1 # to avoid timeout with composer command

  PHP_DATE_TIMEZONE: (Your php timezone) # ex:Africa/Porto-Novo

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - vendor
    - node_modules
    - public
    - .yarn
    - .env

composer:
  stage: preparation
  allow_failure: false # Its there for easy switching
  services:
    - mysql:5.7
    - memcached

before_script:
  - sudo yarn config set cache-folder .yarn
  - mkdir -p public/media/cache && mkdir -p public/media/image # Avoiding error: public/media/image folder not found
script:
  - php -v
  - composer install --prefer-dist --no-ansi --no-scripts --no-interaction --no-progress --no-suggest
artifacts:
  paths:
    - vendor/
    - .env
cache:
  paths:
    - vendor/